tipo = input('Digite algo: ')
print('O tipo desse valor é', type(tipo))
print('Só tem espaços?', tipo.isspace())
print('É um número?', tipo.isnumeric())
print('É um alfabético?', tipo.isalpha())
print('É um alfanumérico?', tipo.isalnum())
print('Está em maiúsculas?', tipo.isupper())
print('Está em minúsculas?', tipo.islower())
print('Está capitalizada?', tipo.istitle())